In [1]:
import pandas as pd

In [2]:
import numpy as np

In [3]:
pd.__version__

'0.25.1'

# Series (data, index, dtype)

In [4]:
s = pd.Series()
s

Series([], dtype: float64)

In [5]:
data = np.arange(0, 100, 10)

In [6]:
data

array([ 0, 10, 20, 30, 40, 50, 60, 70, 80, 90])

In [8]:
s = pd.Series(data)
s

0     0
1    10
2    20
3    30
4    40
5    50
6    60
7    70
8    80
9    90
dtype: int32

In [10]:

s = pd.Series([i for i in range(10, 60, 10)], index=['a', 'b', 'c', 'd', 'e'])
s

a    10
b    20
c    30
d    40
e    50
dtype: int64

In [11]:
s['a']

10

In [13]:
s[0]

10

# Creating Series from dict

In [14]:
dic = {
    "a": 100,
    "b": 200,
    "c": 300
}

In [15]:
dic

{'a': 100, 'b': 200, 'c': 300}

In [16]:
pd.Series(dic)

a    100
b    200
c    300
dtype: int64

In [18]:
for i, j in dic.items():
    print(i, j)

a 100
b 200
c 300


In [20]:
pd.Series([5, 10])

0     5
1    10
dtype: int64

In [22]:
pd.Series(5, index=['a', 'b'])

a    5
b    5
dtype: int64

In [23]:
s

a    10
b    20
c    30
d    40
e    50
dtype: int64

In [24]:
s.index

Index(['a', 'b', 'c', 'd', 'e'], dtype='object')

In [25]:
type(s)

pandas.core.series.Series

In [26]:
s.value_counts

<bound method IndexOpsMixin.value_counts of a    10
b    20
c    30
d    40
e    50
dtype: int64>

In [27]:
s.values

array([10, 20, 30, 40, 50], dtype=int64)

In [28]:
s[1]

20

In [29]:
s

a    10
b    20
c    30
d    40
e    50
dtype: int64

In [30]:
s = pd.Series([i for i in range(10, 110, 10)])

In [31]:
s

0     10
1     20
2     30
3     40
4     50
5     60
6     70
7     80
8     90
9    100
dtype: int64

In [32]:
s[5]

60

In [35]:
for i in s:
    print(i)

10
20
30
40
50
60
70
80
90
100


In [36]:
s

0     10
1     20
2     30
3     40
4     50
5     60
6     70
7     80
8     90
9    100
dtype: int64

In [39]:
s[0:5]

0    10
1    20
2    30
3    40
4    50
dtype: int64

In [40]:
s[2:7]

2    30
3    40
4    50
5    60
6    70
dtype: int64

In [41]:
s.min()

10

In [42]:
s.max()

100

In [43]:
s.mean()

55.0

In [44]:
np.median(s)

55.0

In [45]:
s.std()

30.276503540974915

In [55]:
s = s.append(pd.Series([100]), ignore_index=True)

In [56]:
s

0      10
1      20
2      30
3      40
4      50
5      60
6      70
7      80
8      90
9     100
10    100
11    100
12    100
13    100
dtype: int64

In [57]:
s[0]

10

In [58]:
s[12] = 400

In [59]:
s

0      10
1      20
2      30
3      40
4      50
5      60
6      70
7      80
8      90
9     100
10    100
11    100
12    400
13    100
dtype: int64

In [60]:
del s[12]

In [61]:
s

0      10
1      20
2      30
3      40
4      50
5      60
6      70
7      80
8      90
9     100
10    100
11    100
13    100
dtype: int64

In [62]:
s.values

array([ 10,  20,  30,  40,  50,  60,  70,  80,  90, 100, 100, 100, 100],
      dtype=int64)

In [63]:
s.index

Int64Index([0, 1, 2, 3, 4, 5, 6, 7, 8, 9, 10, 11, 13], dtype='int64')

In [64]:
s.append(pd.Series([100, 200, 300]), ignore_index=True)

0      10
1      20
2      30
3      40
4      50
5      60
6      70
7      80
8      90
9     100
10    100
11    100
12    100
13    100
14    200
15    300
dtype: int64